schema_version: 1

context:
  version: "0.3.0"

package:
  name: ami-mcp
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/03/2e/f61e2a3d72b9726dcedc3af1c0c6c6e46d155bb0b1812dbf81336021c7e4/ami_mcp-${{ version }}.tar.gz
  sha256: 006f7f210bee5f1ebd8b44e25b212475352ba4705355f5afe01ef56cbfbafece

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - ami-mcp=ami_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - pyami-atlas
    - mcp >=2.0.0,<3
    - ca-policy-lcg  # for cert
    - af-credentials >=0.2.0

tests:
  - python:
      imports:
        - ami_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - ami-mcp --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: An MCP server that exposes ATLAS Metadata Information (AMI) operations as tools for LLMs.
  homepage: https://ami-mcp.readthedocs.io/
  repository: https://github.com/kratsg/ami-mcp
  documentation: https://ami-mcp.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
