schema_version: 1

context:
  version: "0.2.3"

package:
  name: ami-mcp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/ami_mcp/ami_mcp-${{ version }}.tar.gz
  sha256: 3fd31026ebddbeca743f93f2ac044d9b4ccab3e4ab01df09c8ac7943e5eadb1c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - ami-mcp=ami_mcp.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - pyami-atlas
    - mcp >=2.0.0,<3
    - ca-policy-lcg  # for cert
    - af-credentials >=0.1.1

tests:
  - python:
      imports:
        - ami_mcp
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - ami-mcp --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: An MCP server that exposes ATLAS Metadata Information (AMI) operations as tools for LLMs.
  homepage: https://ami-mcp.readthedocs.io/
  repository: https://github.com/kratsg/ami-mcp
  documentation: https://ami-mcp.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kratsg
